Remove clang-extract support
SUSE/klp-build pull request #38
Opened 2024-10-26 22:51 UTC by marcosps

2024-10-28 14:55 UTC, fgyanz commented
Error when running `extract` (without `ignore-errors`):
```
File "/klpbuild/cmd.py", line 191, in main_func
    args.avoid_ext, args.ignore_errors).run()
                    ^^^^^^^^^^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'ignore_errors'
```

2024-10-28 14:56 UTC, fgyanz requested changes

2024-10-28 14:56 UTC, fgyanz commented on klp-build.1
> -.RE
Something like:
```
.RE
.TP
.B format-patches
```

2024-10-28 17:27 UTC, marcosps commented
> Error when running `extract` (without `ignore-errors`):
> 
> ```
> File "/klpbuild/cmd.py", line 191, in main_func
>     args.avoid_ext, args.ignore_errors).run()
>                     ^^^^^^^^^^^^^^^^^^
> AttributeError: 'Namespace' object has no attribute 'ignore_errors'
> ```

Ouch, that's true! I forgot to rerun the tests maybe...

2024-10-29 11:40 UTC, fgyanz commented
I'm unsure about where exactly, but apparently for each `extract` thread we are instantiating the configuration file.
```
 Generating livepatches for 11 file(s) using 16 workers...
		Codestream	File
         (1/11) 15.6rtu0        fs/smb/client/cifs_debug.c
         (2/11) 15.6rtu1        fs/smb/client/cifs_debug.c
         (3/11) 15.6rtu2        fs/smb/client/cifs_debug.c
         (4/11) 15.6rtu3        fs/smb/client/cifs_debug.c
         (5/11) 15.6rtu4        fs/smb/client/cifs_debug.c
         (6/11) 15.6u0          fs/smb/client/cifs_debug.c
         (7/11) 15.6u1          fs/smb/client/cifs_debug.c
         (8/11) 15.6u2          fs/smb/client/cifs_debug.c
         (9/11) 15.6u3          fs/smb/client/cifs_debug.c
        (10/11) 15.6u4          fs/smb/client/cifs_debug.c
        (11/11) 15.6u5          fs/smb/client/cifs_debug.c
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
Loading user configuration from '/home/fgonzalez/.config/klp-build/config'
```
Could this be optimized so that we only do it once?

2024-10-29 12:36 UTC, marcosps commented
The issue seems to be that right now I'm instantiating the CCP class inside the process function, and CCP also inherits from Config. One think that I was planning to do was to make Extract be the CCP class, now that we don't have to support more than one backend anymore.

For now I'll try to now depend on Config class anymore. I'll push a new update to this PR later today. Thanks for checking this out!

2024-10-29 13:14 UTC, marcosps commented
@fgyanz should be fixed now!

2024-10-30 10:10 UTC, fgyanz commented
LGTM! Good job!

2024-10-30 10:10 UTC, merged